In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
dataset = pd.read_csv("Data.csv")
dataset.head(10)

Sample code number  Clump Thickness  Uniformity of Cell Size  \
0             1000025                5                        1   
1             1002945                5                        4   
2             1015425                3                        1   
3             1016277                6                        8   
4             1017023                4                        1   
5             1017122                8                       10   
6             1018099                1                        1   
7             1018561                2                        1   
8             1033078                2                        1   
9             1033078                4                        2   

   Uniformity of Cell Shape  Marginal Adhesion  Single Epithelial Cell Size  \
0                         1                  1                            2   
1                         4                  5                            7   
2                         1                  1                            2   
3                         8                  1                            3   
4                         1                  3                            2   
5                        10                  8                            7   
6                         1                  1                            2   
7                         2                  1                            2   
8                         1                  1                            2   
9                         1                  1                            2   

   Bare Nuclei  Bland Chromatin  Normal Nucleoli  Mitoses  Class  
0            1                3                1        1      2  
1           10                3                2        1      2  
2            2                3                1        1      2  
3            4                3                7        1      2  
4            1                3                1        1      2  
5           10                9                7        1      4  
6           10                3                1        1      2  
7            1                3                1        1      2  
8            1                1                1        5      2  
9            1                2                1        1      2

In [3]:
X = dataset.iloc[:,1:-1].values
y = dataset.iloc[:,-1].values

In [4]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,train_size=0.75,random_state=0)

In [5]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

# LOGISTIC

In [6]:
from sklearn.linear_model import LogisticRegression
log_reg = LogisticRegression()
log_reg.fit(X_train,y_train)

LogisticRegression()

In [7]:
log_reg.score(X_train,y_train)*100

98.046875

In [8]:
log_reg.score(X_test,y_test)*100

94.73684210526315

In [9]:
y_pred = log_reg.predict(X_test)
y_pred

array([2, 2, 4, 4, 2, 2, 2, 4, 2, 2, 4, 2, 4, 2, 2, 2, 4, 4, 4, 2, 2, 2,
       4, 2, 4, 4, 2, 2, 2, 4, 2, 4, 4, 2, 2, 2, 4, 4, 2, 4, 2, 2, 2, 2,
       2, 2, 2, 4, 2, 2, 4, 2, 4, 2, 2, 2, 4, 4, 2, 4, 2, 2, 2, 2, 2, 2,
       2, 2, 4, 4, 2, 2, 2, 2, 2, 2, 4, 2, 2, 2, 4, 2, 4, 2, 2, 4, 2, 4,
       4, 2, 4, 2, 4, 4, 2, 4, 4, 4, 4, 2, 2, 2, 4, 4, 2, 2, 4, 2, 2, 2,
       4, 2, 2, 4, 2, 2, 2, 2, 2, 2, 2, 4, 2, 2, 4, 4, 2, 4, 2, 4, 2, 2,
       4, 2, 2, 4, 2, 4, 2, 2, 2, 4, 2, 2, 2, 4, 4, 2, 4, 2, 4, 2, 2, 2,
       2, 2, 4, 4, 2, 4, 4, 4, 4, 2, 4, 2, 2, 2, 2, 2, 2], dtype=int64)

In [10]:
np.concatenate((y_pred.reshape(-1, 1), y_test.reshape(-1, 1)), axis=1)[0:15]

array([[2, 2],
       [2, 2],
       [4, 4],
       [4, 4],
       [2, 2],
       [2, 2],
       [2, 2],
       [4, 4],
       [2, 2],
       [2, 2],
       [4, 4],
       [2, 2],
       [4, 4],
       [2, 2],
       [2, 2]], dtype=int64)

In [11]:
comparison_df = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred})
comparison_df.head(40)

Actual  Predicted
0        2          2
1        2          2
2        4          4
3        4          4
4        2          2
5        2          2
6        2          2
7        4          4
8        2          2
9        2          2
10       4          4
11       2          2
12       4          4
13       2          2
14       2          2
15       2          2
16       4          4
17       4          4
18       4          4
19       2          2
20       2          2
21       2          2
22       4          4
23       2          2
24       4          4
25       4          4
26       2          2
27       2          2
28       2          2
29       4          4
30       2          2
31       4          4
32       4          4
33       2          2
34       2          2
35       2          2
36       4          4
37       4          4
38       2          2
39       4          4

In [12]:
from sklearn.metrics import confusion_matrix , accuracy_score
conf_mat = confusion_matrix(y_pred,y_test)
conf_mat

array([[103,   5],
       [  4,  59]], dtype=int64)

In [13]:
acc_log = accuracy_score(y_pred,y_test)
acc_log

0.9473684210526315

# SVC


In [14]:
from sklearn.svm import SVC
svc = SVC(kernel="linear",random_state=0) # Accuracy 0.93
svc.fit(X_train,y_train)

SVC(kernel='linear', random_state=0)

In [15]:
y_pred_svm = svc.predict(X_test)
y_pred_svm

array([2, 2, 4, 4, 2, 2, 2, 4, 2, 2, 4, 2, 4, 2, 2, 4, 4, 4, 4, 2, 2, 2,
       4, 2, 4, 4, 2, 2, 2, 4, 2, 4, 4, 2, 2, 2, 4, 4, 2, 4, 2, 2, 2, 2,
       2, 2, 2, 4, 2, 2, 4, 2, 4, 2, 2, 2, 4, 4, 2, 4, 2, 2, 2, 2, 2, 2,
       2, 2, 4, 4, 2, 2, 2, 2, 2, 2, 4, 2, 2, 2, 4, 2, 4, 2, 2, 4, 2, 4,
       4, 2, 4, 2, 4, 4, 2, 4, 4, 4, 4, 2, 2, 2, 4, 4, 2, 2, 4, 2, 2, 2,
       4, 2, 2, 4, 2, 2, 2, 2, 2, 2, 2, 4, 2, 2, 4, 4, 2, 4, 2, 4, 2, 2,
       4, 2, 2, 4, 2, 4, 2, 2, 2, 4, 2, 2, 2, 4, 4, 2, 4, 2, 4, 2, 2, 2,
       2, 2, 4, 4, 2, 4, 4, 4, 4, 2, 4, 2, 2, 2, 2, 2, 2], dtype=int64)

In [16]:
np.concatenate((y_pred_svm.reshape(-1, 1), y_test.reshape(-1, 1)), axis=1)[0:15]

array([[2, 2],
       [2, 2],
       [4, 4],
       [4, 4],
       [2, 2],
       [2, 2],
       [2, 2],
       [4, 4],
       [2, 2],
       [2, 2],
       [4, 4],
       [2, 2],
       [4, 4],
       [2, 2],
       [2, 2]], dtype=int64)

In [17]:
comparison_df = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred_svm})
comparison_df.tail(40)

Actual  Predicted
131       2          2
132       4          4
133       2          2
134       2          2
135       4          4
136       2          2
137       4          4
138       2          2
139       2          2
140       2          2
141       4          4
142       2          2
143       2          2
144       2          2
145       2          4
146       4          4
147       2          2
148       4          4
149       2          2
150       4          4
151       4          2
152       2          2
153       2          2
154       2          2
155       2          2
156       4          4
157       4          4
158       2          2
159       4          4
160       4          4
161       4          4
162       4          4
163       4          2
164       4          4
165       2          2
166       2          2
167       2          2
168       2          2
169       2          2
170       2          2

In [18]:
from sklearn.metrics import confusion_matrix , accuracy_score
conf_mat_2 = confusion_matrix(y_pred_svm,y_test)
conf_mat_2

array([[102,   5],
       [  5,  59]], dtype=int64)

In [19]:
acc_in_svm = accuracy_score(y_pred_svm,y_test)
acc_in_svm

0.9415204678362573

# KNN

In [20]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5,metric="minkowski")
knn.fit(X_train,y_train)

KNeighborsClassifier()

In [21]:
y_pred_knn = knn.predict(X_test)
y_pred_knn

array([2, 2, 4, 4, 2, 2, 2, 4, 2, 2, 4, 2, 4, 2, 2, 2, 4, 4, 4, 2, 2, 2,
       4, 2, 4, 4, 2, 2, 2, 4, 2, 4, 4, 2, 2, 2, 4, 4, 2, 4, 2, 2, 2, 2,
       2, 2, 2, 4, 2, 2, 4, 2, 4, 2, 2, 2, 4, 4, 2, 4, 2, 2, 2, 2, 2, 2,
       2, 2, 4, 4, 2, 2, 2, 2, 2, 2, 4, 2, 2, 2, 4, 2, 4, 2, 2, 4, 2, 4,
       4, 2, 4, 2, 4, 4, 2, 4, 4, 4, 4, 2, 2, 2, 4, 4, 2, 2, 4, 2, 2, 2,
       4, 2, 2, 4, 2, 2, 2, 2, 2, 2, 2, 4, 2, 2, 4, 4, 2, 4, 2, 4, 2, 2,
       4, 2, 2, 4, 2, 4, 2, 2, 2, 4, 2, 2, 2, 4, 4, 2, 4, 2, 4, 2, 2, 2,
       2, 2, 4, 4, 2, 4, 4, 4, 4, 2, 4, 2, 2, 2, 2, 2, 2], dtype=int64)

In [22]:
np.concatenate((y_pred_knn.reshape(-1, 1), y_test.reshape(-1, 1)), axis=1)[0:15]

array([[2, 2],
       [2, 2],
       [4, 4],
       [4, 4],
       [2, 2],
       [2, 2],
       [2, 2],
       [4, 4],
       [2, 2],
       [2, 2],
       [4, 4],
       [2, 2],
       [4, 4],
       [2, 2],
       [2, 2]], dtype=int64)

In [23]:
from sklearn.metrics import confusion_matrix , accuracy_score
conf_mat_3 = confusion_matrix(y_pred_svm,y_test)
conf_mat_3

array([[102,   5],
       [  5,  59]], dtype=int64)

In [24]:
acc_knn = accuracy_score(y_pred_knn,y_test)
acc_knn

0.9473684210526315

# DECISION TREE

In [25]:
from sklearn.tree import DecisionTreeClassifier
dec_tree = DecisionTreeClassifier(criterion='entropy',random_state=0)
dec_tree.fit(X_train,y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [26]:
y_pred_dec = dec_tree.predict(X_test)
y_pred_dec

array([2, 2, 4, 4, 2, 2, 2, 4, 2, 2, 4, 2, 4, 2, 2, 2, 4, 4, 4, 2, 2, 2,
       4, 2, 4, 4, 2, 2, 2, 4, 2, 4, 4, 2, 2, 2, 4, 4, 2, 4, 2, 2, 2, 2,
       2, 2, 2, 4, 2, 2, 4, 2, 4, 2, 2, 2, 4, 4, 2, 4, 2, 2, 2, 2, 2, 2,
       2, 2, 4, 4, 2, 2, 2, 2, 2, 2, 4, 2, 2, 2, 4, 2, 4, 2, 2, 4, 2, 4,
       4, 2, 4, 2, 4, 2, 4, 2, 4, 4, 2, 2, 2, 2, 4, 4, 2, 2, 4, 4, 2, 2,
       4, 2, 2, 4, 2, 2, 2, 2, 2, 2, 2, 4, 2, 2, 4, 4, 2, 4, 2, 4, 2, 2,
       4, 2, 2, 4, 2, 4, 2, 2, 2, 2, 2, 2, 2, 4, 4, 2, 4, 2, 4, 4, 2, 2,
       2, 2, 4, 4, 2, 4, 4, 4, 4, 4, 4, 2, 2, 2, 2, 2, 2], dtype=int64)

In [27]:
np.concatenate((y_pred_knn.reshape(-1, 1), y_test.reshape(-1, 1)), axis=1)[0:15]

array([[2, 2],
       [2, 2],
       [4, 4],
       [4, 4],
       [2, 2],
       [2, 2],
       [2, 2],
       [4, 4],
       [2, 2],
       [2, 2],
       [4, 4],
       [2, 2],
       [4, 4],
       [2, 2],
       [2, 2]], dtype=int64)

In [28]:
from sklearn.metrics import confusion_matrix , accuracy_score
conf_mat_4 = confusion_matrix(y_pred_dec,y_test)
conf_mat_4

array([[104,   4],
       [  3,  60]], dtype=int64)

In [29]:
acc_dec = accuracy_score(y_pred_dec,y_test)
acc_dec

0.9590643274853801

# RANDOM FOREST

In [30]:
from sklearn.ensemble import RandomForestClassifier
rand_for = RandomForestClassifier(n_estimators=10,random_state=0)
rand_for.fit(X_train,y_train)

RandomForestClassifier(n_estimators=10, random_state=0)

In [31]:
y_pred_rand = rand_for.predict(X_test)
y_pred_rand

array([2, 2, 4, 4, 2, 2, 2, 4, 2, 2, 4, 2, 4, 2, 2, 2, 4, 4, 4, 2, 2, 2,
       4, 2, 4, 4, 2, 2, 2, 4, 2, 4, 4, 2, 2, 2, 4, 4, 2, 4, 2, 2, 2, 2,
       2, 2, 2, 4, 2, 2, 4, 2, 4, 2, 2, 2, 4, 4, 2, 4, 2, 2, 2, 2, 2, 2,
       2, 2, 4, 4, 2, 2, 2, 2, 2, 2, 4, 2, 2, 2, 4, 2, 4, 2, 2, 4, 2, 4,
       4, 2, 4, 2, 4, 2, 2, 2, 4, 4, 4, 2, 2, 2, 4, 4, 2, 2, 4, 2, 2, 2,
       4, 2, 2, 4, 2, 2, 2, 4, 2, 2, 2, 4, 2, 2, 4, 4, 2, 4, 2, 4, 2, 2,
       4, 2, 2, 4, 2, 4, 2, 2, 2, 2, 2, 2, 2, 4, 4, 2, 2, 2, 4, 2, 2, 2,
       2, 2, 4, 4, 2, 4, 4, 4, 4, 2, 4, 2, 2, 2, 2, 2, 2], dtype=int64)

In [32]:
np.concatenate((y_pred_rand.reshape(-1, 1), y_test.reshape(-1, 1)), axis=1)[0:15]

array([[2, 2],
       [2, 2],
       [4, 4],
       [4, 4],
       [2, 2],
       [2, 2],
       [2, 2],
       [4, 4],
       [2, 2],
       [2, 2],
       [4, 4],
       [2, 2],
       [4, 4],
       [2, 2],
       [2, 2]], dtype=int64)

In [33]:
from sklearn.metrics import confusion_matrix, accuracy_score
cnf_mat_5 = confusion_matrix(y_pred_rand,y_test)
cnf_mat_5

array([[104,   7],
       [  3,  57]], dtype=int64)

In [34]:
acc_random =  accuracy_score(y_pred_rand,y_test)
acc_random

0.9415204678362573

# NAIVE BAYES

In [35]:
from sklearn.naive_bayes import GaussianNB
nb_class = GaussianNB()
nb_class.fit(X_train,y_train)

GaussianNB()

In [36]:
y_pred_nb = nb_class.predict(X_test)
print(y_pred_rand)
print()
print()
print(np.concatenate((y_pred_nb.reshape(-1, 1), y_test.reshape(-1, 1)), axis=1)[0:15])

[2 2 4 4 2 2 2 4 2 2 4 2 4 2 2 2 4 4 4 2 2 2 4 2 4 4 2 2 2 4 2 4 4 2 2 2 4
 4 2 4 2 2 2 2 2 2 2 4 2 2 4 2 4 2 2 2 4 4 2 4 2 2 2 2 2 2 2 2 4 4 2 2 2 2
 2 2 4 2 2 2 4 2 4 2 2 4 2 4 4 2 4 2 4 2 2 2 4 4 4 2 2 2 4 4 2 2 4 2 2 2 4
 2 2 4 2 2 2 4 2 2 2 4 2 2 4 4 2 4 2 4 2 2 4 2 2 4 2 4 2 2 2 2 2 2 2 4 4 2
 2 2 4 2 2 2 2 2 4 4 2 4 4 4 4 2 4 2 2 2 2 2 2]


[[2 2]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [2 2]]


In [37]:
from sklearn.metrics import confusion_matrix, accuracy_score
cnf_mat_6 = confusion_matrix(y_pred_nb,y_test)
print(cnf_mat_6)
acc_nb = accuracy_score(y_pred_nb,y_test)
print()
print()
print(acc_nb)

[[100   3]
 [  7  61]]


0.9415204678362573


In [38]:
max(acc_dec,acc_in_svm,acc_knn,acc_nb,acc_random,acc_log)

0.9590643274853801

In [39]:
# DECISION TREE GIVES MAX ACCURACY